In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(review, vocab_size) for review in reviews]
encoded_reviews

[[18, 9],
 [8, 18],
 [2, 12],
 [10, 1, 5],
 [15, 3, 28],
 [26, 9],
 [24, 3, 6],
 [20, 4],
 [20, 26],
 [21, 2]]

In [6]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[18  9  0  0]
 [ 8 18  0  0]
 [ 2 12  0  0]
 [10  1  5  0]
 [15  3 28  0]
 [26  9  0  0]
 [24  3  6  0]
 [20  4  0  0]
 [20 26  0  0]
 [21  2  0  0]]


In [7]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [8]:
X = padded_reviews
y= sentiment

In [9]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X,y,epochs=50,verbose=0)

In [11]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 101ms/step - loss: 0.6184 - accuracy: 1.0000


In [15]:
weight = model.get_layer('embedding').get_weights()[0]
len(weight)


30